ERROR 2022-09-27 18:08:57,067 connection.py _receive_response 206 [52b4876a-941f-440f-85a5-10baeff7bce7]: no such element
ERROR 2022-09-27 18:08:58,633 assertbase.py _teardown_collect 273 <bound method FirstTest.test_02_add_device_index of <minitest.FirstTest testMethod=test_02_add_device_index>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/framework/libs/unittest/case.py", line 32, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/framework/libs/unittest/case.py", line 118, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/isentech/Desktop/python/miniu_test/minitest.py", line 26, in test_02_add_device_index
    self.page.get_element("/page/view/view[3]/view[1]/view[1]/view/view/view/view/view/view/view[1]/input").input(de.device_mac)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/minium_log.py", line 135, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/page.py", line 200, in get_element
    return self.get_element_by_xpath(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/minium_log.py", line 135, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/page.py", line 387, in get_element_by_xpath
    raise MiniElementNotFoundError("element[%s] not found" % xpath)
minium.framework.exception.MiniElementNotFoundError: element[/page/view/view[3]/view[1]/view[1]/view/view/view/view/view/view/view[1]/input] not found
