ERROR 2022-09-28 19:07:18,091 connection.py _receive_response 206 [8d807c2d-b5d4-4abf-aff3-40649e51b8ee]: page "/*[@id="listDOM"]/device-item/view/view[1]" is not found
ERROR 2022-09-28 19:07:18,753 assertbase.py _teardown_collect 273 <bound method FirstTest.test_02_add_device_index of <minitest.FirstTest testMethod=test_02_add_device_index>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/framework/libs/unittest/case.py", line 32, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/framework/libs/unittest/case.py", line 118, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/isentech/Desktop/python/miniu_test/minitest.py", line 35, in test_02_add_device_index
    page = self.app.navigate_to('//*[@id="listDOM"]/device-item/view/view[1]')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/minium_log.py", line 135, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/app.py", line 308, in navigate_to
    page = self._change_route("navigateTo", url, is_wait_url_change)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/app.py", line 475, in _change_route
    self.call_wx_method(open_type, [{"url": path}])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/minium_log.py", line 135, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/app.py", line 247, in call_wx_method
    return self._call_wx_method(method=method, args=args, plugin_appid=plugin_appid)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/minium_object.py", line 287, in _call_wx_method
    return self.connection.send("App.callWxMethod", params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/connection.py", line 185, in send
    return self._receive_response(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/connection.py", line 207, in _receive_response
    raise MiniAppError(err_msg)
minium.framework.exception.MiniAppError: page "/*[@id="listDOM"]/device-item/view/view[1]" is not found
