ERROR 2022-09-21 12:07:34,972 assertbase.py _teardown_collect 273 <bound method FirstTest.test_01_bing_device of <minitest.FirstTest testMethod=test_01_bing_device>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/framework/libs/unittest/case.py", line 32, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/framework/libs/unittest/case.py", line 118, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/isentech/Desktop/python/miniu_test/minitest.py", line 17, in test_01_bing_device
    bing_device_page=self.page.path()
TypeError: 'str' object is not callable
ERROR 2022-09-21 12:21:41,118 assertbase.py _teardown_collect 273 <bound method FirstTest.test_01_bing_device of <minitest.FirstTest testMethod=test_01_bing_device>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/framework/libs/unittest/case.py", line 32, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/framework/libs/unittest/case.py", line 118, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/isentech/Desktop/python/miniu_test/minitest.py", line 17, in test_01_bing_device
    self.page.path()
TypeError: 'str' object is not callable
