ERROR 2022-09-28 18:53:14,124 connection.py _receive_response 206 [7fe81bc8-b103-483b-a849-105d03d42530]: no such element
ERROR 2022-09-28 18:53:15,660 assertbase.py _teardown_collect 273 <bound method FirstTest.test_08_auto_add_device of <minitest.FirstTest testMethod=test_08_auto_add_device>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/framework/libs/unittest/case.py", line 32, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/framework/libs/unittest/case.py", line 118, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/isentech/Desktop/python/miniu_test/minitest.py", line 68, in test_08_auto_add_device
    self.page.get_element('//*[@id="showUi"]/button').click()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/minium_log.py", line 135, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/page.py", line 200, in get_element
    return self.get_element_by_xpath(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/minium_log.py", line 135, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/page.py", line 387, in get_element_by_xpath
    raise MiniElementNotFoundError("element[%s] not found" % xpath)
minium.framework.exception.MiniElementNotFoundError: element[//*[@id="showUi"]/button] not found
