ERROR 2022-09-28 14:09:07,555 connection.py _receive_response 206 [1e7cb6a2-036e-4b48-a377-3b8377d05938]: no such element
ERROR 2022-09-28 14:09:09,117 assertbase.py _teardown_collect 273 <bound method FirstTest.test_04_click_navigation of <minitest.FirstTest testMethod=test_04_click_navigation>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/framework/libs/unittest/case.py", line 32, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/framework/libs/unittest/case.py", line 118, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/isentech/Desktop/python/miniu_test/minitest.py", line 44, in test_04_click_navigation
    self.page.get_element('//*[@id="devicePopup"]/view[7]/view[1]').click()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/minium_log.py", line 135, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/page.py", line 200, in get_element
    return self.get_element_by_xpath(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/minium_log.py", line 135, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minium/miniprogram/base_driver/page.py", line 387, in get_element_by_xpath
    raise MiniElementNotFoundError("element[%s] not found" % xpath)
minium.framework.exception.MiniElementNotFoundError: element[//*[@id="devicePopup"]/view[7]/view[1]] not found
